src/App.tsx, src/main.tsx, src/page/SignUp/index.tsx, src/page/SnackBar/index.tsx, src/ts/useSnackBar.tsx
에러 핸들링 훅을 추가 했습니다.
SnackBar 컴포넌트는 3초 후 자동으로 닫힘
사용방법
1. const onError = useSnackBar()
2. fetch 함수 내부에서 catch 부분에 onError를 에러 객체를 담아서 사용
사용해보시고 불편한 점이나 개선할만한 내용 말씀해주세요
Close #13
=> Feature/#13 에러 핸들링 훅 추가

src/query/members.ts
리액트 쿼리에서 쿼리키가 누락되어 리렌더링이 되지 않던 버그를 수정했습니다.
Close #46
=> [회원관리] 탈퇴회원 정보수정 시 렌더링이 되지 않던 버그 수정

src/component/modal/memberCreateModal/index.tsx, src/page/MemberInfo/ListLayout/index.tsx, src/page/MemberInfo/TrackFilter/index.tsx, src/page/MemberInfo/index.tsx, src/page/MemberInfo/style.ts
- 비밀번호 암호화 적용 및 테스트 완료했습니다.
- 회원생성 버튼을 하단으로 이동시키고, 트랙필터 버튼의 width를 줄여 상단의 버튼 공간을 확보했습니다.
- 회원생성에 성공하면 폼을 초기화 시키도록 수정했습니다.
- 데이터 필드 width를 조절하여 메카트로닉스공학부 글자가 짤리지 않도록 수정하였습니다.
Close #70 Close #71 Close #73 Close #74
=> [회원생성] 비밀번호 SHA256암호화, 버튼 충돌 수정, 생성 후 폼 초기화

src/page/MemberInfo/ListLayout/index.tsx, src/page/MemberInfo/index.tsx
- 회원권한이 `ADMIN` `MANAGER` 일때만 회원정보 수정, 회원정보 생성 버튼을 렌더링하도록 수정했습니다.
버튼이 밀리는현상은 다른 PR에서 처리하였으나, 아직 merge가 안 되어있는 상태입니다.
Close #54
=> [회원정보] 회원 권한에 따라 수정, 생성 접근 제한

src/page/MyPage/index.tsx, src/page/MyPage/style.ts
- 프로필 이미지가 null인 경우 기본 프로필 사진을 보여줍니다.
Close #52
=> [마이페이지] 프로필 이미지 미업로드시 기본 프로필 적용

src/component/modal/memberInfoModal/index.tsx, src/index.css, src/layout/SideBar/index.tsx, src/model/member.ts, src/page/MemberInfo/GridLayout/index.tsx, src/page/MemberInfo/GridLayout/style.ts, src/page/MemberInfo/ListLayout/index.tsx, src/page/MemberInfo/index.tsx, src/page/MemberInfo/style.ts
- 그리드 레이아웃으로 회원정보를 조회할 수 있도록 구현했습니다.
- 각 그리드 컨테이너를 눌러 회원정보를 수정할 수 있습니다(admin, manager 권한을 가진경우)
- Close #55
=> [회원정보] 그리드 레이아웃 구현

src/page/DuesManagement/index.tsx, src/page/DuesManagement/style.ts, src/page/DuesSetup/index.tsx, src/page/DuesSetup/style.ts, src/page/EditDues/index.tsx, src/page/EditDues/style.ts, src/util/constants/status.ts
- 회비 생성, 회비 납부, 회비 수정 모든 페이지에 이름을 통한 `오름차순` `내림차순` 기능을 추가했습니다.
- `회비 납부` 페이지에서 미납 혹은 면제 사유를 볼 수 있는 팝오버 이슈를 해결하였습니다.
- 사유가 없다면 `사유 없음` 사유 클릭 후 다른 사유를 볼 때 이전 값이 출력되는 문제를 해결하였습니다.
- 표를 넘길 때 다음 연도에 대한 값이 없는 경우 버튼을 `disabled`로 수정하였습니다.
https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/74540646/7e13251a-1779-4397-8518-6178fad9bcb4
- Close #58, #59, #64, #67
=> 회비 납부 페이지, 회비 수정 페이지 이슈 해결

src/App.tsx, src/api/members/index.ts, src/model/member.ts, src/page/FindPassword/index.tsx, src/page/FindPassword/style.ts, src/page/SignIn/index.tsx, src/page/SignIn/style.ts
비밀번호 찾기 페이지는 비밀번호를 변경하는 방식으로 동작합니다.
이메일, 인증번호, 새 비밀번호를 단계에 맞게 입력하고
요청이 성공하면 비밀번호가 변경되며 로그인 화면으로 이동합니다.
추가적으로 회원가입 승인 페이지에 페이지네이션을 적용했습니다.
- Close #83 
- Close #72
=> [비밀번호 찾기] 비밀번호 찾기 페이지 추가

src/layout/SideBar/index.tsx, src/layout/SideBar/style.ts, src/layout/TopBar/index.tsx
사이드바에 회비 그룹을 만들어서 회비 버튼 클릭시 회비 관리 리스트가 보이도록 변경했습니다.
pr에 올려주신 내용을 참고하여 현재 위치한 페이지의 버튼에 background-color를 변경했습니다.
- Close #65 
- Close #66
=> [공통] 사이드바 회비 그룹 생성 및 스타일 수정

src/page/Admin/index.tsx, src/page/MemberInfo/GridLayout/index.tsx, src/page/MemberInfo/GridLayout/style.ts, src/page/MemberInfo/ListLayout/index.tsx, src/page/MemberInfo/index.tsx, src/page/MemberInfo/style.ts, src/page/SignUp/index.tsx
- 회원승인 페이지 상단 margin 추가
- 회원정보 페이지에서 탈퇴 회원 토글을 하단으로 이동하여 트랙 정보 width 여유공간 제공
- 회원정보 그리드레이아웃에서 이메일 폰트크기를 줄이고, padding을 줄여 더 많은 정보를 한줄에 제공
- 회원가입 페이지에서 label을 다른 페이지들과 통일
- Close #98
- Close #99 
- Close #101 
- Close #104
=> 2차 스프린트 UI 이슈 해결

src/page/DuesManagement/index.tsx, src/page/EditDues/index.tsx
- 회비 페이지에서 멘토 인원을 `filter` 메서드를 통해 삭제
- 표에 없는 인원을 검색 시 검색할 수 없다고 에러 처리 추가
- 트랙 필터 default 값 추가
- Close #103
=> [회비] 회비 페이지 멘토 인원 삭제

src/page/Reservation/index.tsx, src/page/Reservation/view/Week/index.tsx, src/page/Reservation/view/Week/modal/modifyReservationModal/index.tsx
- 지난 시간은 선택하지 못하도록 수정했습니다!
https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/74540646/560dc1f1-804b-451c-8c37-434033e76d97
- Close #140
=> [동방 예약] 지난 시간은 선택하지 못하도록 수정

src/page/DuesManagement/index.tsx, src/page/EditDues/index.tsx
- 미납 횟수 순서 정렬 추가했습니다!
- 기존에 `오름차순` `내림차순`을 나타내는 화살표가 반대로 되어 있어 수정했습니다.
https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/74540646/8b095534-66d1-4cbe-a3b1-1d95c394b5ba
- Close #152
=> [회비 납부] 미납 횟수 순서 정렬 추가

src/page/Reservation/view/Week/index.tsx, src/page/Reservation/view/Week/modal/displayTime/index.tsx, src/page/Reservation/view/Week/modal/displayTimeAndReason/index.tsx, src/page/Reservation/view/Week/modal/displayTimeAndReason/style.ts, src/page/Reservation/view/Week/styles.ts, src/util/constants/time.ts
- 전체 코드에서 분의 범위를 설정하지 않아 생기는 에러로 파악
- 기존 `MINUTE_LIST`를 수정함 ('10' -> '00-10')
https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/74540646/360de161-a946-414e-9f43-024ce1fb6e6f
https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/74540646/4f53dafb-36de-41a0-95ca-4e5637731467
- Close #159
=> [동방 예약] 시간이 10분 밀리는 현상 해결

src/layout/SideBar/index.tsx
내일 스프린트 종료 이후 배포이전 미구현 된 페이지를 사용자에게 보여주지 않기위해 라우팅을 제거했습니다.
주소에 `/team`을 검색하면 접속가능하지만 사이드바에서만 제거했습니다.
- Close #163
=> 미구현 페이지 라우팅 제거

src/api/admin/index.ts, src/layout/TopBar/index.tsx, src/layout/TopBar/style.ts, src/model/admin.ts, src/query/admin.ts
- 공통 헤더에 슬랙 동기화 버튼을 추가했습니다.
- 아이디의 권한이 `ADMIN`, `MANGER`일 때만 보입니다.
- Close #ISSUE_NUMBER
=> [슬랙봇] 슬랙 동기화 버튼 추가

src/layout/SideBar/style.ts, src/layout/TopBar/style.ts, src/util/hooks/useMediaQuery.ts
- 공통으로 사용하는 sidebar, topbar의 모바일 뷰 css 추가 (글씨 크기 및 버튼 크기, 사이드바 전체 크기를 알맞게 수정)
- useMediaQuery 추가
**Topbar에서 가장 긴 타이틀을 예시로 가져왔습니다.**
- emotion에서 사용하는 방식이 기존 scss와 달라 사용하는 방법 공유드립니다.
useMediaQuery에 `mobile`을 통해 모바일 css를 따로 추가할 수 있습니다.
``` ts
import { mobile } from 'util/hooks/useMediaQuery';
export const buttonContainer = css`
display: flex;
justify-content: flex-end;
gap: 20px;
${mobile} {
button {
font-size: 12px;
width: 65px;
height: 35px;
padding: 0;
}
}
`;
```
- Close #ISSUE_NUMBER
=> [공통] useMediaQuery 추가 및 공통 페이지 모바일 뷰 추가

src/query/members.ts
- getMe API 호출시 401에러가 발생하면 로컬스토리지를 삭제하는 로직을 추가했습니다.
- Close #186
=> [에러핸들링] getMe API호출시 에러 핸들링 추가

index.html
- 인터널 도메인이 구글검색에 나오는 이슈가 있었습니다.
- 검색로봇이 페이지를 찾을 수 없게 차단합니다.
=> [공통] 검색로봇 차단 태그 추가

src/component/YearPagination/index.tsx, src/page/DuesManagement/index.tsx, src/page/EditDues/index.tsx, src/page/PersonalDues/index.tsx
회비 내역 수정 페이지네이션 버그 해결
페이지네이션 전부 `dues` 페이지로 이동하는 버그를 `Pagination` props를 pageName으로 받아 에러 해결
- Close #195
=> [회비 관리] 페이지네이션 에러 수정

src/api/dues/index.ts, src/page/EditDues/components/AlertModal/index.tsx, src/page/EditDues/components/AlertModal/style.ts, src/page/EditDues/index.tsx, src/query/dues.ts
- 회비 납부 문서의 내역 동기화 기능 API 버튼 추가
아직 API가 만들어지지 않아 단순히 버튼을 통해 api 요청(dues/sheet-sync)만 가기 때문에 제대로 기능 동작이 하지 않습니다!
- Close #ISSUE_NUMBER
=> [회비] 회비 납부 문서를 인터널 DB에 반영하는 회비 내역 동기화 기능 추가
